name: windows-2019

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/.windows.yml
    with:
      os: windows-2019
      send_coverage: false
